use: pipeline
kind: character
name: nefer

combat:
  icd_tags:
    - Nefer_ElementalBurst

talents:
  - attack:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - attack(3-Hit DMG)
      - attack(4-Hit DMG)
  - charge: attack(Charged Attack DMG)
  - collision_plunge: attack(Plunge DMG)
  - low_plunge: attack(Low/High Plunge DMG) # {}/{}
  - high_plunge: attack(Low/High Plunge DMG|1) # {}/{}

  - skill_att: skill(Skill DMG)
  - skill_em: skill(Skill DMG|1)
  - phantasm_nefer_1_att: skill(Phantasm Performance 1-Hit DMG (Nefer)) # {} ATK+{} Elemental Mastery
  - phantasm_nefer_1_em: skill(Phantasm Performance 1-Hit DMG (Nefer)|1) # {} ATK+{} Elemental Mastery
  - phantasm_nefer_2_att: skill(Phantasm Performance 2-Hit DMG (Nefer)) # {} ATK+{} Elemental Mastery
  - phantasm_nefer_2_em: skill(Phantasm Performance 2-Hit DMG (Nefer)|1) # {} ATK+{} Elemental Mastery
  - phantasm_shade_1_em: skill(Phantasm Performance 1-Hit DMG (Shades))
  - phantasm_shade_2_em: skill(Phantasm Performance 2-Hit DMG (Shades))
  - phantasm_shade_3_em: skill(Phantasm Performance 3-Hit DMG (Shades))

  - vow_1_att: burst(1-Hit DMG) # {} ATK+{} Elemental Mastery
  - vow_1_em: burst(1-Hit DMG|1) # {} ATK+{} Elemental Mastery
  - vow_2_att: burst(2-Hit DMG) # {} ATK+{} Elemental Mastery
  - vow_2_em: burst(2-Hit DMG|1) # {} ATK+{} Elemental Mastery
  - veil_bonus: burst(DMG Bonus)
